services:
  java-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-application
    ports:
      - 8080:8080
    restart: always
    networks:
      - default
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - 3309:3306
    restart: always
    networks:
      - default
    volumes:
      - shared-data:/var/lib/mysql
    env_file:
      - .env
  k6:
    image: loadimpact/k6
    container_name: k6
    networks:
      - default
    depends_on:
      - java-application
    volumes:
      - ./k6:/scripts  # 로컬 디렉토리를 컨테이너의 /scripts 디렉토리로 마운트
    entrypoint: ["k6", "run", "/scripts/your-test-script.js"]

networks:
  default:
    driver: bridge

volumes:
  shared-data: